Repository Beyond-Article1/MediHub-FE, pull requests merged in 2024-12, with the labels that each got.

#4 [FEAT] Header 개발
  medihub-fe/src/App.vue
  medihub-fe/src/assets/images/MEDIHUB.png
  medihub-fe/src/components/Header.vue
  medihub-fe/src/router/cpRouter.js
  medihub-fe/src/views/cp/CpDetail.vue
  medihub-fe/src/views/cp/CpMain.vue
Labels: :new: feat

#5 [FEAT] 공용컴포넌트 개발
  medihub-fe/src/App.vue
  medihub-fe/src/components/common/DropBox.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/common/LineDivider.vue
  medihub-fe/src/components/common/SearchBox.vue
  medihub-fe/src/components/cp/CpBody.vue
  medihub-fe/src/components/cp/CpHeader.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
  medihub-fe/src/components/cp/CpTitle.vue
  medihub-fe/src/router/index.js
  medihub-fe/src/views/cp/CpMain.vue
Labels: :new: feat

#8 [FEAT] 채팅방 화면 개발, 웹 CSS 기본 설정 초기화
  medihub-fe/package-lock.json
  medihub-fe/package.json
  medihub-fe/src/App.vue
  medihub-fe/src/assets/images/chat/Communication.png
  medihub-fe/src/assets/images/chat/Communication_Navy.png
  medihub-fe/src/assets/images/chat/FileExplorer.png
  medihub-fe/src/assets/images/chat/FlowChart.png
  medihub-fe/src/assets/images/chat/MediHub_LOGO.png
  medihub-fe/src/assets/images/chat/profile.png
  medihub-fe/src/components/chat/ChatButton.vue
  medihub-fe/src/components/chat/ChatroomDetail.vue
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/FileBox.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/main.js
  medihub-fe/src/styles/reset.css
  medihub-fe/src/views/chat/ChatWindow.vue
Labels: :new: feat

#12 [FEAT] #11 bookmark 버튼 컴포넌트 제작
  medihub-fe/src/assets/images/after-bookmark.png
  medihub-fe/src/components/BookmarkButton.vue
  medihub-fe/src/views/BestJournalView.vue
Labels: :new: feat

#14 [FEAT] 로그인 화면 구현
  medihub-fe/package-lock.json
  medihub-fe/package.json
  medihub-fe/src/main.js
  medihub-fe/src/router/index.js
  medihub-fe/src/router/loginRouter.js
  medihub-fe/src/router/mainRouter.js
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/main/Main.vue
Labels: :new: feat

#17 [FEAT] #16 좋아요버튼 컴포넌트 제작, Journal 수정
  medihub-fe/src/assets/images/arrow/drop-arrow.png
  medihub-fe/src/assets/images/arrow/up-arrow.png
  medihub-fe/src/assets/images/bookmark/after-bookmark.png
  medihub-fe/src/assets/images/bookmark/before-bookmark.png
  medihub-fe/src/assets/images/heart/after-heart.png
  medihub-fe/src/assets/images/heart/before-heart.png
  medihub-fe/src/components/button/BookmarkButton.vue
  medihub-fe/src/components/button/HeartButton.vue
  medihub-fe/src/components/button/JournalSortButtonGroup.vue
  medihub-fe/src/components/button/SortButton.vue
  medihub-fe/src/views/BestJournalView.vue
Labels: :hammer_and_wrench: fix, :new: feat

#19 [FEAT] axios 인터셉터 설정
  medihub-fe/src/components/common/button/BookmarkButton.vue
  medihub-fe/src/components/common/button/HeartButton.vue
  medihub-fe/src/components/common/button/JournalSortButtonGroup.vue
  medihub-fe/src/components/common/button/SortButton.vue
  medihub-fe/src/main.js
Labels: :new: feat

#20 [FEAT] 중간 push
  medihub-fe/src/components/common/Pagenation.vue
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/BestJournalView.vue
Labels: :hammer_and_wrench: fix, :new: feat

#22 [FEAT] #18 페이지네이션 컴포넌트
  medihub-fe/src/components/common/Pagenation.vue
  medihub-fe/src/views/BestJournalView.vue
Labels: :hammer_and_wrench: fix, :new: feat

#24 [REFACTOR] 로그인 페이지 수정
  medihub-fe/src/App.vue
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/login/Login.vue
Labels: :recycle: refactor

#26 [FEAT] CP 조회 VIEW 개발
  medihub-fe/package-lock.json
  medihub-fe/package.json
  medihub-fe/public/icons/marker.png
  medihub-fe/public/pdfs/sample.pdf
  medihub-fe/src/components/common/DropBox.vue
  medihub-fe/src/components/common/LocalDateTimeFormat.vue
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/common/SortButton.vue
  medihub-fe/src/components/common/button/BookmarkButton.vue
  medihub-fe/src/components/common/button/Button.vue
  medihub-fe/src/components/cp/CpBody.vue
  medihub-fe/src/components/cp/CpContent.vue
  medihub-fe/src/components/cp/CpHeader.vue
  medihub-fe/src/components/cp/CpLi.vue
  medihub-fe/src/components/cp/CpLiInfo.vue
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/components/cp/CpListBody.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
  medihub-fe/src/router/cpRouter.js
  medihub-fe/src/styles/reset.css
  medihub-fe/src/views/cp/CpDetail.vue
  medihub-fe/src/views/cp/CpMain.vue
Labels: :new: feat

#27 [FEAT] 메디컬라이프(수정예정) 및 회원 정보 조회 수정
  medihub-fe/src/App.vue
  medihub-fe/src/router/index.js
  medihub-fe/src/router/medicalLifeRouter.js
  medihub-fe/src/router/userRouter.js
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/medical_life/MedicalLife.vue
  medihub-fe/src/views/user/UserDetail.vue
Labels: :new: feat

#32 [FIX] JournalBestView 수정
  medihub-fe/src/assets/images/send.png
  medihub-fe/src/router/journalRouter.js
  medihub-fe/src/views/journal/BestJournalView.vue
  medihub-fe/src/views/journal/MediH.vue
Labels: :hammer_and_wrench: fix, :new: feat

#35 [FEAT] 웹소켓 설정, 채팅 기능
  medihub-fe/index.html
  medihub-fe/src/assets/images/chat/Attach.png
  medihub-fe/src/assets/images/chat/NewChat-Navy.png
  medihub-fe/src/components/chat/ChatroomDetail.vue
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/FileBox.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/chat/ChatWindow.vue
  medihub-fe/src/views/login/Login.vue
Labels: :new: feat

#36 [FEAT] sse connect/#33
  medihub-fe/package-lock.json
  medihub-fe/package.json
  medihub-fe/src/assets/images/check.png
  medihub-fe/src/assets/images/x.png
  medihub-fe/src/components/common/Pagination.vue
  medihub-fe/src/router/index.js
  medihub-fe/src/router/testRouter.js
  medihub-fe/src/views/SseConnectTest.vue
  medihub-fe/src/views/case_sharing/template/TemplateListView.vue
  medihub-fe/src/views/journal/BestJournalView.vue
  medihub-fe/src/views/medical_life/MedicalLife.vue
Labels: :hammer_and_wrench: fix, :new: feat

#39 [FIX] 페이지네이션 이름 변경
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingList.vue
  medihub-fe/src/views/case_sharing/template/TemplateListView.vue
Labels: :hammer_and_wrench: fix

#42 REFACTOR: 페이지네이션
  medihub-fe/src/views/admin/AdminUser.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
  medihub-fe/src/views/user/AllUser.vue
Labels: :recycle: refactor

#43 [FEAT] CP 뷰 개발
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/common/LocalDateTimeFormat.vue
  medihub-fe/src/components/common/MultiSelectDropBox.vue
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/common/SingleSelectDropBox.vue
  medihub-fe/src/components/common/button/IconButton.vue
  medihub-fe/src/components/common/button/svgIconButton.vue
  medihub-fe/src/components/cp/CpContent.vue
  medihub-fe/src/components/cp/CpLi.vue
  medihub-fe/src/components/cp/CpModal.vue
  medihub-fe/src/components/cp/CpOpinionLi.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
  medihub-fe/src/router/cpRouter.js
  medihub-fe/src/styles/reset.css
  medihub-fe/src/views/cp/cp-opinion/CpOpinionDetail.vue
  medihub-fe/src/views/cp/cp-opinion/CpOpinionRegister.vue
  medihub-fe/src/views/cp/cp-opinion/CpOpinionUpdate.vue
  medihub-fe/src/views/cp/cp/CpDetail.vue
  medihub-fe/src/views/cp/cp/CpMain.vue
Labels: :new: feat

#45 [FEAT] 조직도 조회, 채팅방 생성
  medihub-fe/src/App.vue
  medihub-fe/src/assets/images/chat/Back.png
  medihub-fe/src/assets/images/chat/Default_Profile.png
  medihub-fe/src/assets/images/chat/Vector-Down.png
  medihub-fe/src/assets/images/chat/Vector-Right.png
  medihub-fe/src/components/chat/ChatroomDetail.vue
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/FileBox.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/chat/ChatWindow.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :new: feat

#47 [FEAT] 익명 게시판, Elasticsearch 화면 구현
  medihub-fe/src/assets/images/anonymousBoard/empty-profile.png
  medihub-fe/src/assets/images/like/after-like.png
  medihub-fe/src/assets/images/like/before-like.png
  medihub-fe/src/components/anonymousBoard/AnonymousBoardEditor.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardLineDivider.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardList.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardSaveButton.vue
  medihub-fe/src/components/anonymousBoard/BoardKeywordInput.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/common/SearchBox.vue
  medihub-fe/src/components/common/button/HeartButton.vue
  medihub-fe/src/components/common/button/LikeButton.vue
  medihub-fe/src/router/anonymousBoardRouter.js
  medihub-fe/src/router/index.js
  medihub-fe/src/views/anonymousBoard/AnonymousBoardCreateView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardDetailView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardEditView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardListView.vue
  medihub-fe/src/views/medical_life/MedicalLife.vue
Labels: :new: feat, :1234: chore

#49 [FEAT] 메인 제작
  medihub-fe/src/assets/images/doctor.png
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/main/HotContents.vue
  medihub-fe/src/components/main/MonthlyTop.vue
  medihub-fe/src/components/main/NewsSection.vue
  medihub-fe/src/views/main/Main.vue
Labels: :new: feat, :recycle: refactor

#48 [FEAT] CP 뷰 개발
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/common/SearchBox.vue
  medihub-fe/src/components/cp/CpHeader.vue
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/router/cpRouter.js
  medihub-fe/src/store/searchStore.js
  medihub-fe/src/views/cp/cp-opinion/CpOpinionDetail.vue
Labels: :new: feat

#51 [FIX] SearchBox 수정
  medihub-fe/src/components/common/SearchBox.vue
Labels: :hammer_and_wrench: fix

#52 [FEAT] journal, medi-h 90% 완성
  medihub-fe/package-lock.json
  medihub-fe/package.json
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/router/journalRouter.js
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingEditView.vue
  medihub-fe/src/views/journal/BestJournalView.vue
  medihub-fe/src/views/journal/MediH.vue
Labels: :hammer_and_wrench: fix, :new: feat

#59 [FEAT] 채팅방 내 세부 기능 구현
  medihub-fe/src/App.vue
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/ChatroomNameModal.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/chat/ParticipantListModal.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/components/common/SearchBox.vue
  medihub-fe/src/store/chatStore.js
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/chat/ChatroomWindow.vue
  medihub-fe/src/views/login/Login.vue
Labels: :new: feat, :recycle: refactor

#60 [FEAT] CP 뷰 개발
  medihub-fe/src/components/common/Board.vue
  medihub-fe/src/components/common/Card.vue
  medihub-fe/src/components/common/InputModal.vue
  medihub-fe/src/components/cp/CpHeader.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
  medihub-fe/src/router/cpRouter.js
  medihub-fe/src/store/searchStore.js
  medihub-fe/src/styles/reset.css
  medihub-fe/src/views/cp/admin/CpSearchCategoryDataManagement.vue
  medihub-fe/src/views/cp/admin/CpSearchCategoryManagement.vue
Labels: :new: feat

#61 [FEAT] #57 sse component 헤더에 연결 및 모달화
  medihub-fe/src/assets/images/after-notify.png
  medihub-fe/src/assets/images/before-notify.png
  medihub-fe/src/components/NotificationModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/router/index.js
  medihub-fe/src/router/testRouter.js
  medihub-fe/src/views/SseConnectTest.vue
Labels: :hammer_and_wrench: fix, :new: feat

#62 [FEAT] 메디컬라이프 및 회원
  medihub-fe/src/components/medicallife/MedicalLifeEditor.vue
  medihub-fe/src/components/medicallife/MedicalLifeKeywordinput.vue
  medihub-fe/src/components/medicallife/MedicalLifeLineDivider.vue
  medihub-fe/src/components/medicallife/MedicalLifeList.vue
  medihub-fe/src/components/medicallife/MedicalLifeSaveButtion.vue
  medihub-fe/src/components/user/MyPage.vue
  medihub-fe/src/router/MyPageRouter.js
  medihub-fe/src/router/adminRouter.js
  medihub-fe/src/router/index.js
  medihub-fe/src/router/medicalLifeRouter.js
  medihub-fe/src/views/admin/AdminUser.vue
  medihub-fe/src/views/admin/AdminUserDetail.vue
  medihub-fe/src/views/admin/CreateUser.vue
  medihub-fe/src/views/admin/DeptManage.vue
  medihub-fe/src/views/admin/PartManage.vue
  medihub-fe/src/views/admin/RankManage.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardDetailView.vue
  medihub-fe/src/views/medical_life/MedicalLife.vue
  medihub-fe/src/views/medical_life/MedicalLifeCreate.vue
  medihub-fe/src/views/medical_life/MedicalLifeDetail.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
  medihub-fe/src/views/user/AllUser.vue
  medihub-fe/src/views/user/MyPage.vue
Labels: :new: feat

#65 [FIX] #64 testRouter 제거
  medihub-fe/src/router/index.js
Labels: :hammer_and_wrench: fix

#67 [FEAT] 케이스 공유 관련 추가 구현
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingCategory.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingContent.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBar.vue
  medihub-fe/src/components/case_sharing/case_sharing/DraftModal.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentListModal.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentModal.vue
  medihub-fe/src/components/case_sharing/template/TemplateCreateModal.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingCreateView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingDetailView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingEditView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingListView.vue
  medihub-fe/src/views/case_sharing/template/TemplateListView.vue
  medihub-fe/src/views/chatbot/ChatbotWindow.vue
  medihub-fe/src/views/cp/cp-opinion/CpOpinionRegister.vue
Labels: :new: feat, :recycle: refactor, :1234: chore

#70 [FEAT] 첨부파일 전송 기능, [REFACTOR] 채팅 화면 컴포넌트화
  medihub-fe/src/assets/images/chat/default-file-icon.png
  medihub-fe/src/assets/images/chat/excel-icon.png
  medihub-fe/src/assets/images/chat/pdf-icon.png
  medihub-fe/src/assets/images/chat/word-icon.png
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/MessageItem.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/store/chatStore.js
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/chat/ChatWindow.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :new: feat, :recycle: refactor

#72 [FEAT] 파일함 기능
  medihub-fe/src/components/chat/FileBox.vue
Labels: :new: feat

#74 [FEAT] #73 cicd 파이프라인 생성 및 테스트
  .github/workflows/main.yml
Labels: :hammer_and_wrench: fix, :new: feat

#79 [FEAT] 메인페이지 내 의료 뉴스 컴포넌트
  medihub-fe/src/components/main/NewsSection.vue
Labels: :new: feat

#80 [REFACTOR] 마이페이지 코드 수정
  medihub-fe/src/views/admin/AdminUserDetail.vue
  medihub-fe/src/views/admin/CreateUser.vue
  medihub-fe/src/views/admin/RankManage.vue
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/medical_life/MedicalLifeDetail.vue
  medihub-fe/src/views/medical_life/MedicalLifeEdit.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
  medihub-fe/src/views/mypage/AnonymousBoardView.vue
  medihub-fe/src/views/mypage/CPView.vue
  medihub-fe/src/views/mypage/FollowMemberView.vue
  medihub-fe/src/views/mypage/MedicalLifeView.vue
  medihub-fe/src/views/mypage/MyCaseSharingView.vue
  medihub-fe/src/views/mypage/MyJournalView.vue
  medihub-fe/src/views/user/AllUser.vue
Labels: :recycle: refactor

#82 [FEAT] 메시지 삭제 기능, 채팅방/조직도 내 검색 기능
  medihub-fe/src/components/chat/ChatButton.vue
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/FileBox.vue
  medihub-fe/src/components/chat/MessageItem.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/store/authStore.js
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/chat/ChatWindow.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :new: feat, :1234: chore

#84 [FIX] CP PDF 뷰어 오류 수정
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/common/SingleSelectDropBox.vue
  medihub-fe/src/components/cp/CpContent.vue
  medihub-fe/src/components/cp/CpLi.vue
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
  medihub-fe/src/router/cpRouter.js
  medihub-fe/src/store/cpCategoryStore.js
  medihub-fe/src/views/cp/cp_opinion/CpOpinionDetail.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionRegister.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionUpdate.vue
Labels: :hammer_and_wrench: fix

#88 [HOTFIX] 뉴스 기사 호출 주석 처리
  medihub-fe/src/components/main/NewsSection.vue
Labels: :hammer_and_wrench: fix

#90 [FEAT] 채팅방 프로필 사진, 검색 기능 추가
  medihub-fe/src/assets/images/chat/download.png
  medihub-fe/src/assets/images/chat/group-chat.png
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/MessageItem.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :new: feat

#92 [FEAT] 익명 게시판 화면 수정
  medihub-fe/src/components/anonymousBoard/AnonymousBoardEditor.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardKeywordList.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardSaveButton.vue
  medihub-fe/src/components/anonymousBoard/BoardKeywordInput.vue
  medihub-fe/src/router/anonymousBoardRouter.js
  medihub-fe/src/views/anonymousBoard/AnonymousBoardCreateView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardDetailView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardEditView.vue
Labels: :new: feat, :recycle: refactor
