Repository Beyond-Article1/MediHub-FE, pull requests merged in 2025-01, with the labels that each got.

#97 [FEAT] CP 페이지네이션 기능 개발
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/components/cp/CpModal.vue
Labels: :new: feat

#101 [FIX] CP 각종 오류 수정
  medihub-fe/src/components/common/Pagination.vue
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/cp/CpContent.vue
  medihub-fe/src/components/cp/CpModal.vue
Labels: :hammer_and_wrench: fix

#103 [REFACTOR] 시큐리티 및 메디컬 라이프
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/main/HotContents.vue
  medihub-fe/src/components/user/MyPage.vue
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/medical_life/MedicalLifeDetail.vue
  medihub-fe/src/views/mypage/CPView.vue
Labels: :recycle: refactor

#105 [FEAT] [FIX] CP 오류 해결
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/cp/CpLi.vue
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/components/cp/CpModal.vue
  medihub-fe/src/components/cp/CpOpinionLi.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionDetail.vue
Labels: :hammer_and_wrench: fix, :new: feat

#108 [REFACTOR] CP 의견 내용 컴포넌트 코드 리펙토링
  medihub-fe/src/components/cp/CpOpinionContent.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionDetail.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionRegister.vue
Labels: :recycle: refactor

#111 [REFACTOR] 익명 게시판 화면 수정
  medihub-fe/src/components/anonymousBoard/AnonymousBoardEditor.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardList.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardSearchBox.vue
  medihub-fe/src/components/anonymousBoard/BoardKeywordInput.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardDetailView.vue
Labels: :recycle: refactor

#114 [FIX] 채팅 프로필 사진 경로 수정
  medihub-fe/public/chat/download.png
  medihub-fe/public/chat/excel-icon.png
  medihub-fe/public/chat/group-chat.png
  medihub-fe/public/chat/pdf-icon.png
  medihub-fe/public/chat/profile.png
  medihub-fe/public/chat/word-icon.png
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/FileBox.vue
  medihub-fe/src/components/chat/MessageItem.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/chat/ParticipantListModal.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/chat/ChatWindow.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :hammer_and_wrench: fix

#117 [FIX]랭킹 수정 및 마이페이지 라우팅 처리
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/admin/AdminUser.vue
  medihub-fe/src/views/journal/BestJournalView.vue
  medihub-fe/src/views/journal/MediH.vue
  medihub-fe/src/views/mypage/AnonymousBoardView.vue
  medihub-fe/src/views/mypage/CPView.vue
  medihub-fe/src/views/mypage/MedicalLifeView.vue
  medihub-fe/src/views/mypage/MyCaseSharingView.vue
  medihub-fe/src/views/mypage/MyJournalView.vue
  medihub-fe/src/views/user/AllUser.vue
  medihub-fe/src/views/user/UserDetail.vue
Labels: :hammer_and_wrench: fix, :recycle: refactor

#119 [REFACTOR] [FIX] 다운로드 실패 오류 해결, CSS 수정
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/cp/CpLi.vue
  medihub-fe/src/components/cp/CpModal.vue
  medihub-fe/src/components/cp/CpOpinionContent.vue
  medihub-fe/src/components/cp/CpOpinionDetailContent.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionDetail.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionRegister.vue
Labels: :hammer_and_wrench: fix, :recycle: refactor

#85 [REFACTOR] 케이스 공유 리펙토링
  medihub-fe/src/components/NotificationModal.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingEditor.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBar.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentListModal.vue
  medihub-fe/src/components/case_sharing/template/TemplateCreateModal.vue
  medihub-fe/src/components/main/HotContents.vue
  medihub-fe/src/components/main/MonthlyTop.vue
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingCreateView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingDetailView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingEditView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingListView.vue
  medihub-fe/src/views/case_sharing/template/TemplateListView.vue
Labels: :new: feat, :recycle: refactor

#122 [FEAT] 마이페이지 검색 기능
  medihub-fe/src/router/adminRouter.js
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/admin/AdminUser.vue
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/user/AllUser.vue
Labels: :new: feat, :recycle: refactor

#124 [REFACTOR] 파일함 내 첨부파일 구분 카테고리 세분화
  medihub-fe/src/components/chat/FileBox.vue
Labels: :recycle: refactor

#77 test: #75 cicd-test v1
  .github/workflows/main.yml
  medihub-fe/index.html
  medihub-fe/public/favicon.ico
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingCategory.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBar.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/main.js
  medihub-fe/src/store/authStore.js
  medihub-fe/src/store/webSocket.js
  medihub-fe/src/views/CicdTestView.vue
  medihub-fe/src/views/admin/AdminUser.vue
  medihub-fe/src/views/admin/AdminUserDetail.vue
  medihub-fe/src/views/admin/CreateUser.vue
  medihub-fe/src/views/admin/DeptManage.vue
  medihub-fe/src/views/admin/PartManage.vue
  medihub-fe/src/views/admin/RankManage.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionRegister.vue
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
  medihub-fe/src/views/mypage/FollowMemberView.vue
  medihub-fe/src/views/user/AllUser.vue
  medihub-fe/src/views/user/UserDetail.vue
Labels: :hammer_and_wrench: fix, :new: feat

#127 [HOTFIX] pdfjs-dist 라이브러리의 UnknownErrorException 오류 해결
  medihub-fe/package-lock.json
  medihub-fe/package.json
  medihub-fe/src/components/common/PdfViewer.vue
Labels: :hammer_and_wrench: fix

#129 [FEAT] CP 관련 UX 향상 코드 추가
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/views/cp/admin/CpSearchCategoryDataManagement.vue
  medihub-fe/src/views/cp/admin/CpSearchCategoryManagement.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionDetail.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionUpdate.vue
Labels: :new: feat

#131 [REFACTOR] 경로 라우터 가드
  medihub-fe/src/router/adminRouter.js
  medihub-fe/src/router/anonymousBoardRouter.js
  medihub-fe/src/router/caseSharingRouter.js
  medihub-fe/src/router/journalRouter.js
  medihub-fe/src/router/mainRouter.js
  medihub-fe/src/router/medicalLifeRouter.js
  medihub-fe/src/router/mypagedetailRouter.js
  medihub-fe/src/router/userRouter.js
Labels: :recycle: refactor

#133 [FEAT] CP 라우터 권한 확인 기능 개발
  medihub-fe/src/router/cpRouter.js
Labels: :new: feat

#136 [FEAT] 익명 게시판 화면 수정
  medihub-fe/src/components/anonymousBoard/AnonymousBoardEditor.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardList.vue
  medihub-fe/src/components/main/HotContents.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardCreateView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardDetailView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardEditView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardListView.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
Labels: :new: feat, :1234: chore

#139 [STYLE] 화면 CSS 수정, console.log 정리
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/MessageItem.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/store/chatStore.js
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :rainbow: style

#143 [FIX] authstore 수정
  medihub-fe/src/store/authStore.js
Labels: :hammer_and_wrench: fix

#141 [REFACTOR] 로그 삭제, content 수정
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingCategory.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingContent.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingEditor.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBar.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBox.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingVersion.vue
  medihub-fe/src/components/case_sharing/case_sharing/DraftModal.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentListModal.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentModal.vue
  medihub-fe/src/components/main/MonthlyTop.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingCreateView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingDetailView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingEditView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingListView.vue
  package-lock.json
Labels: :recycle: refactor, :1234: chore

#146 [FIX] 로그인 중복 화면 수정
  medihub-fe/src/App.vue
Labels: :hammer_and_wrench: fix

#147 [FIX] 로그 삭제
  medihub-fe/src/store/authStore.js
Labels: :hammer_and_wrench: fix

#150 [FIX] 데이터 나오는 console.log 제거
  medihub-fe/src/components/NotificationModal.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/common/PdfViewer.vue
  medihub-fe/src/components/cp/CpContent.vue
  medihub-fe/src/components/cp/CpHeader.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionRegister.vue
  medihub-fe/src/views/journal/BestJournalView.vue
  medihub-fe/src/views/journal/MediH.vue
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/medical_life/MedicalLifeDetail.vue
  medihub-fe/src/views/user/AllUser.vue
  medihub-fe/src/views/user/UserDetail.vue
Labels: :hammer_and_wrench: fix

#153 [CHORE] 메인 페이지 Elasticsearch 화면 수정
  medihub-fe/src/store/authStore.js
  medihub-fe/src/views/search/SearchAllView.vue
  medihub-fe/src/views/search/SearchBoardView.vue
  medihub-fe/src/views/search/SearchCaseView.vue
  medihub-fe/src/views/search/SearchLifeView.vue
Labels: :1234: chore

#158 [REFACTOR] 불필요 로그 제거
  medihub-fe/src/App.vue
  medihub-fe/src/components/NotificationModal.vue
  medihub-fe/src/components/anonymousBoard/AnonymousBoardList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBar.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentListModal.vue
  medihub-fe/src/components/case_sharing/case_sharing_comment/CommentModal.vue
  medihub-fe/src/components/chat/ChatroomList.vue
  medihub-fe/src/components/chat/Organization.vue
  medihub-fe/src/components/chat/SelectUserModal.vue
  medihub-fe/src/components/common/Header.vue
  medihub-fe/src/components/cp/CpLi.vue
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
  medihub-fe/src/components/main/HotContents.vue
  medihub-fe/src/config/test.md
  medihub-fe/src/main.js
  medihub-fe/src/routers/adminRouter.js
  medihub-fe/src/routers/anonymousBoardRouter.js
  medihub-fe/src/routers/caseSharingRouter.js
  medihub-fe/src/routers/cpRouter.js
  medihub-fe/src/routers/index.js
  medihub-fe/src/routers/journalRouter.js
  medihub-fe/src/routers/loginRouter.js
  medihub-fe/src/routers/mainRouter.js
  medihub-fe/src/routers/medicalLifeRouter.js
  medihub-fe/src/routers/mypagedetailRouter.js
  medihub-fe/src/routers/searchRouter.js
  medihub-fe/src/routers/userRouter.js
  medihub-fe/src/stores/authStore.js
  medihub-fe/src/stores/chatStore.js
  medihub-fe/src/stores/cpCategoryStore.js
  medihub-fe/src/stores/webSocket.js
  medihub-fe/src/views/anonymousBoard/AnonymousBoardCreateView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardDetailView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardEditView.vue
  medihub-fe/src/views/anonymousBoard/AnonymousBoardListView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingCreateView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingDetailView.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingEditView.vue
  medihub-fe/src/views/case_sharing/template/TemplateListView.vue
  medihub-fe/src/views/chat/ChatWindow.vue
  medihub-fe/src/views/chat/ChatroomWindow.vue
  medihub-fe/src/views/chatbot/ChatbotWindow.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionDetail.vue
  medihub-fe/src/views/cp/cp_opinion/CpOpinionRegister.vue
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/main/Main.vue
  medihub-fe/src/views/medical_life/MedicalLifeCreate.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
  medihub-fe/src/views/search/SearchAllView.vue
  medihub-fe/src/views/search/SearchBoardView.vue
  medihub-fe/src/views/search/SearchCaseView.vue
  medihub-fe/src/views/search/SearchLifeView.vue
Labels: :recycle: refactor

#162 [FIX] #161 notify
  medihub-fe/src/components/common/Header.vue
Labels: :hammer_and_wrench: fix

#166 [FIX] 채팅 메시지 중복 이슈 수정
  medihub-fe/src/stores/webSocket.js
  medihub-fe/src/views/chat/ChatroomWindow.vue
Labels: :hammer_and_wrench: fix

#167 [FIX] 오류 수정
  medihub-fe/src/stores/authStore.js
  medihub-fe/src/views/login/Login.vue
  medihub-fe/src/views/medical_life/Medical_Life.vue
  medihub-fe/src/views/mypage/AnonymousBoardView.vue
  medihub-fe/src/views/mypage/MedicalLifeView.vue
Labels: :hammer_and_wrench: fix, :recycle: refactor

#169 [FIX] CP 의견 조회 에러 해결
  medihub-fe/src/components/cp/CpOpinionDetailContent.vue
Labels: :hammer_and_wrench: fix

#171 [FIX] 권환 확인 로직 수정
  medihub-fe/src/routers/cpRouter.js
Labels: :hammer_and_wrench: fix

#175 [CHORE] 불필요 로그 주석화
  medihub-fe/src/components/cp/CpList.vue
  medihub-fe/src/components/cp/CpSearchCategory.vue
Labels: :rainbow: style

#176 [FIX] 로그인 로직 정리
  medihub-fe/src/stores/authStore.js
  medihub-fe/src/views/login/Login.vue
Labels: :hammer_and_wrench: fix, :recycle: refactor

#179 [FIX] #173 메디컬 라이프 CSS 수정
  medihub-fe/src/views/medical_life/Medical_Life.vue
Labels: :hammer_and_wrench: fix

#181 [CHORE] css 수정
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingVersion.vue
  medihub-fe/src/components/main/MonthlyTop.vue
  medihub-fe/src/views/case_sharing/template/TemplateListView.vue
Labels: :rainbow: style, :1234: chore

#182 [REFACTOR]: 메디컬 라이프 CSS 수정
  medihub-fe/src/views/medical_life/Medical_Life.vue
Labels: :recycle: refactor

#184 [REFACTOR] Elasticsearch 화면 수정
  medihub-fe/src/components/anonymousBoard/AnonymousBoardList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingList.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBar.vue
  medihub-fe/src/components/case_sharing/case_sharing/CaseSharingSearchBox.vue
  medihub-fe/src/views/case_sharing/case_sharing/CaseSharingListView.vue
Labels: :recycle: refactor, :wastebasket: delete

#178 fix: #177 뉴스 기사 조회 주석 제거
  medihub-fe/src/components/main/NewsSection.vue
Labels: :hammer_and_wrench: fix
